# Generated by Django 3.0.8 on 2020-08-12 05:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20200812_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+61450728861', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
