# Generated by Django 3.0.8 on 2020-08-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_auto_20200821_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shopping/banner')),
                ('title', models.CharField(default='Awesome!! You landed in the right place!!', max_length=100)),
                ('additional_info', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
