# Generated by Django 3.0.8 on 2020-08-21 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
    ]
