# Generated by Django 3.0.8 on 2020-08-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_auto_20200825_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemOrder',
            new_name='OrderItem',
        ),
    ]
