# Generated by Django 3.0.8 on 2020-08-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0018_auto_20200826_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='shopping.ItemOrder', to='shopping.Item'),
        ),
    ]
