# Generated by Django 3.0.8 on 2020-08-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0019_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
