# Generated by Django 3.0.8 on 2020-08-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0020_remove_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemorder',
            old_name='count',
            new_name='quantity',
        ),
    ]
