# Generated by Django 3.0.8 on 2020-08-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0023_auto_20200828_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='alt_image',
            field=models.SlugField(blank=True, max_length=10),
        ),
    ]
