# Generated by Django 3.1.1 on 2020-09-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0029_auto_20200918_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='shopping/uploads/profile'),
        ),
    ]
