# Generated by Django 3.1.1 on 2020-09-24 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0032_auto_20200921_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='item',
            name='topping',
        ),
        migrations.CreateModel(
            name='CustomItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='shopping.item')),
                ('flavor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flavor_items', to='shopping.flavor')),
                ('topping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topping_items', to='shopping.topping')),
            ],
        ),
    ]
