# Generated by Django 3.1.1 on 2020-09-24 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0034_auto_20200924_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='flavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.flavor'),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.topping'),
        ),
    ]
