# Generated by Django 3.1.2 on 2020-10-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0035_auto_20200924_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='available_flavors',
            field=models.ManyToManyField(related_name='items_with_flavor', to='shopping.Flavor'),
        ),
        migrations.AlterField(
            model_name='item',
            name='available_toppings',
            field=models.ManyToManyField(related_name='items_with_topping', to='shopping.Topping'),
        ),
        migrations.AddField(
            model_name='item',
            name='flower',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flower_items', to='shopping.flower'),
        ),
    ]
