# Generated by Django 3.1.2 on 2020-10-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0036_auto_20201008_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='customitem',
            name='size',
            field=models.TextField(default='Small', max_length=10),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='size',
            field=models.TextField(default='Small', max_length=10),
        ),
    ]
